import {projectPoint,inverse3,inside,validateProject} from './embedded-math.mjs';
const $=id=>document.getElementById(id),c=$('stage'),ctx=c.getContext('2d'),key='spatial-take-embedded-v1';
let project,baseline,scene,index=0,selected=0,expanded=null,playing=false,original=false,drawing=null,cache=new Map(),generation=0;
function persist(){localStorage.setItem(key,JSON.stringify(project))}
function ob(){return scene.objects[selected]}
function matrix(o){return scene.tracks[o.track]?.[index]?.h??null}
function polygon(o){const h=matrix(o);return h?o.poly.map(p=>projectPoint(h,p)):null}
function status(s){$('status').textContent=s}
function form(){const o=ob();$('inspector').hidden=!o;if(!o)return;$('label').value=o.name;$('detail').value=o.info;$('kind').value=o.kind;$('value').value=o.value;$('enabled').checked=o.enabled;$('action').textContent=o.checked?'Undo checked':o.action||'Mark checked'}
function objectList(){$('objects').replaceChildren();scene.objects.forEach((o,i)=>{const b=document.createElement('button');b.textContent=(o.enabled?'● ':'○ ')+o.name;b.classList.toggle('active',i===selected);b.onclick=()=>{selected=i;expanded=o.id;objectList();form();render()};$('objects').append(b)})}
function selectScene(i){playing=false;scene=project.scenes[i];index=scene.reference;selected=0;expanded=null;drawing=null;cache.clear();$('seek').max=scene.count-1;$('play').textContent='Play';[...$('scenes').children].forEach((b,j)=>b.classList.toggle('active',j===i));objectList();form();return render()}
function menu(){$('scenes').replaceChildren();project.scenes.forEach((s,i)=>{const b=document.createElement('button');b.textContent=s.title;b.onclick=()=>selectScene(i);$('scenes').append(b)})}
function image(n){const u=scene.frames+String(n).padStart(5,'0')+'.jpg';if(!cache.has(u)){cache.set(u,new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('Missing frame '+u));im.src=u}));if(cache.size>90)cache.delete(cache.keys().next().value)}return cache.get(u)}
function path(points){ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath()}
// Tessellated projective texture mapping: the label follows the physical plane, not the screen.
function tri(im,s,d){const [a,b,e]=s,[A,B,E]=d,det=(b[0]-a[0])*(e[1]-a[1])-(e[0]-a[0])*(b[1]-a[1]);if(Math.abs(det)<1e-8)return;const x1=B[0]-A[0],x2=E[0]-A[0],y1=B[1]-A[1],y2=E[1]-A[1];const m1=(x1*(e[1]-a[1])-x2*(b[1]-a[1]))/det,m3=(x2*(b[0]-a[0])-x1*(e[0]-a[0]))/det,m2=(y1*(e[1]-a[1])-y2*(b[1]-a[1]))/det,m4=(y2*(b[0]-a[0])-y1*(e[0]-a[0]))/det;ctx.save();path(d);ctx.clip();ctx.transform(m1,m2,m3,m4,A[0]-m1*a[0]-m3*a[1],A[1]-m2*a[0]-m4*a[1]);ctx.drawImage(im,0,0);ctx.restore()}
function quadMap(q,u,v){const [a,b,c,d]=q;const dx1=b[0]-c[0],dx2=d[0]-c[0],dx3=a[0]-b[0]+c[0]-d[0],dy1=b[1]-c[1],dy2=d[1]-c[1],dy3=a[1]-b[1]+c[1]-d[1],det=dx1*dy2-dx2*dy1;let g=0,h=0;if(Math.abs(det)>1e-9){g=(dx3*dy2-dx2*dy3)/det;h=(dx1*dy3-dx3*dy1)/det}return [(a[0]+(b[0]-a[0]+g*b[0])*u+(d[0]-a[0]+h*d[0])*v)/(1+g*u+h*v),(a[1]+(b[1]-a[1]+g*b[1])*u+(d[1]-a[1]+h*d[1])*v)/(1+g*u+h*v)]}
function texture(im,q){const n=8;for(let y=0;y<n;y++)for(let x=0;x<n;x++){const uv=[[x/n,y/n],[(x+1)/n,y/n],[(x+1)/n,(y+1)/n],[x/n,(y+1)/n]],s=uv.map(([u,v])=>[u*im.width,v*im.height]),d=uv.map(([u,v])=>quadMap(q,u,v));tri(im,[s[0],s[1],s[2]],[d[0],d[1],d[2]]);tri(im,[s[0],s[2],s[3]],[d[0],d[2],d[3]])}}
function label(o){const t=document.createElement('canvas');t.width=640;t.height=220;const g=t.getContext('2d');g.fillStyle='rgba(10,30,23,.85)';g.fillRect(0,0,640,220);g.fillStyle=o.checked?'#b3d7bd':'#d9fff0';g.fillRect(0,0,8,220);g.font='600 64px system-ui';g.fillText((o.checked?'✓ ':'')+o.name,26,65,590);g.font='42px system-ui';g.fillStyle='#b9e5cc';g.fillText(expanded===o.id?o.detail:o.info,26,118,590);if(o.kind==='progress'){g.fillStyle='#365345';g.fillRect(26,159,585,13);g.fillStyle='#8ad9b1';g.fillRect(26,159,585*o.value,13);g.font='20px system-ui';g.fillText(Math.round(o.value*100)+'% · demo',26,204)}else if(expanded===o.id){g.font='23px system-ui';g.fillText(o.checked?'Checked':o.action||'Mark checked',26,185)}return t}
async function render(){const token=++generation;const im=await image(index);if(token!==generation)return;ctx.clearRect(0,0,720,720);ctx.drawImage(im,0,0,720,720);let visible=0;if(!original)for(const o of scene.objects){if(!o.enabled)continue;const h=matrix(o),p=polygon(o);if(!h||!p?.every(p=>p.every(Number.isFinite)))continue;visible++;path(p);ctx.fillStyle=o.checked?'rgba(116,192,147,.06)':'rgba(134,235,185,.12)';ctx.fill();ctx.strokeStyle=o.checked?'#a0bbae':'#a5efd0';ctx.lineWidth=expanded===o.id?3:1.3;ctx.stroke();if(o.kind!=='highlight')texture(label(o),o.quad.map(p=>projectPoint(h,p)))}if(drawing){ctx.fillStyle='#ffe398';for(const [x,y]of drawing){ctx.beginPath();ctx.arc(x,y,5,0,7);ctx.fill()}}$('seek').value=index;$('clock').textContent=(index/scene.fps).toFixed(2)+' s';status(drawing?`Click ${4-drawing.length} more corners clockwise on the same physical plane.`:`${scene.title} · ${visible} tracked overlays · ${original?'Original footage':'Click a physical target to inspect / act'}`);window.embeddedState={scene:scene.id,index,visible,selected:ob()?.id,expanded};return window.embeddedState}
function xy(e){const r=c.getBoundingClientRect();return[(e.clientX-r.left)*720/r.width,(e.clientY-r.top)*720/r.height]}
c.onclick=e=>{const p=xy(e);if(drawing){drawing.push(p);if(drawing.length===4){const o=ob(),inv=inverse3(matrix(o));if(!inv){drawing=null;status('Target tracking unavailable');return}const q=drawing.map(p=>projectPoint(inv,p));const n={...structuredClone(o),id:'surface-'+Date.now(),name:'NEW SURFACE',info:'Edit this embedded label',poly:q,quad:q,enabled:true,checked:false};scene.objects.push(n);selected=scene.objects.length-1;drawing=null;persist();objectList();form()}render();return}for(let i=scene.objects.length-1;i>=0;i--){const o=scene.objects[i],p2=polygon(o);if(o.enabled&&p2&&inside(p,p2)){selected=i;expanded=expanded===o.id?null:o.id;form();objectList();render();return}}};
for(const id of ['label','detail','kind','value','enabled'])$(id).oninput=()=>{const o=ob();if(!o)return;o.name=$('label').value;o.info=$('detail').value;o.kind=$('kind').value;o.value=Number($('value').value);o.enabled=$('enabled').checked;persist();objectList();render()};
$('action').onclick=()=>{ob().checked=!ob().checked;persist();form();render()};$('delete').onclick=()=>{scene.objects.splice(selected,1);selected=0;persist();objectList();form();render()};
$('add').onclick=()=>{if(!ob()||!matrix(ob())){status('Select a currently tracked target first.');return}playing=false;drawing=[];render()};
$('seek').oninput=()=>{index=Number($('seek').value);render()};$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'Pause':'Play'};
$('before').onpointerdown=()=>{original=true;render()};for(const ev of ['pointerup','pointercancel','pointerleave'])$('before').addEventListener(ev,()=>{original=false;render()});
$('save').onclick=()=>{const blob=new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='embedded-project.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
$('load').onchange=async()=>{try{const p=JSON.parse(await $('load').files[0].text());validateProject(p);project=p;persist();menu();await selectScene(0)}catch(e){status('Import rejected: '+e.message)}};
$('reset').onclick=()=>{project=structuredClone(baseline);persist();menu();selectScene(0)};
let last=performance.now(),busy=false;setInterval(async()=>{const now=performance.now();if(playing&&!busy){const steps=Math.floor((now-last)/1000*scene.fps);if(steps){last=now;index=(index+steps)%scene.count;busy=true;try{await render()}finally{busy=false}}}else last=now},16);
try{baseline=await(await fetch('./private/embedded/project.json')).json();validateProject(baseline);try{project=JSON.parse(localStorage.getItem(key));validateProject(project)}catch{project=structuredClone(baseline)}menu();await selectScene(0);window.embeddedReady=true;window.embedded={selectScene,render:async n=>{index=n;return render()},export:()=>structuredClone(project)}}catch(e){status('Cannot load embedded project: '+e.message);throw e}
