import * as T from 'three';
import {setPose,frameAt} from './math.mjs';
import {paint} from './inspiration50-paint.mjs';
const $=s=>document.querySelector(s),base='./sessions/quest-215403/';
const [session,catalog,room,tracks,hands]=await Promise.all([fetch(base+'session.json').then(r=>r.json()),fetch('./docs/inspiration50-catalog.json').then(r=>r.json()),fetch(base+'room-geometry.json').then(r=>r.json()),fetch('/audit/bottle-track.json').then(r=>r.json()),fetch(base+'hands.jsonl').then(r=>r.text()).then(s=>s.trim().split('\n').map(JSON.parse))]);
if(session.synthetic||session.name!=='20261002_215403')throw Error('This study requires the actual Quest take 20261002_215403.');
const S=900,renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(S,S);renderer.outputColorSpace=T.SRGBColorSpace;renderer.setClearColor(0,0);$('#view').append(renderer.domElement);renderer.domElement.id='renderer';renderer.domElement.style.display='none';
const scene=new T.Scene(),camera=new T.PerspectiveCamera(),world=new T.Group(),solid=new T.Group();scene.add(world,solid);scene.add(new T.AmbientLight(0xffffff,2));const sun=new T.DirectionalLight(0xffedca,3);sun.position.set(2,4,3);scene.add(sun);
const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=768;const ctx=canvas.getContext('2d'),tex=new T.CanvasTexture(canvas);tex.colorSpace=T.SRGBColorSpace;
const dc=document.createElement('canvas');dc.width=dc.height=320;const dx=dc.getContext('2d',{willReadFrequently:true});const depths=new Map(),images=new Map(),anchors={};let current=-1,layer,last=-1,bg,dep,playing=false,elapsed=0,trigger=0,words='',busy=false;
const rd={value:null};const mat=new T.MeshBasicMaterial({map:tex,transparent:true,side:T.DoubleSide,depthWrite:false});mat.onBeforeCompile=s=>{s.uniforms.rd=rd;s.vertexShader='varying float az;\n'+s.vertexShader.replace('#include <project_vertex>','#include <project_vertex>\naz=-mvPosition.z;');s.fragmentShader='uniform sampler2D rd; varying float az;\n'+s.fragmentShader.replace('#include <clipping_planes_fragment>',`#include <clipping_planes_fragment>\nvec4 d=texture2D(rd,gl_FragCoord.xy/${S}.0);float z=(d.r*65280.0+d.g*255.0)/1000.0;if(d.b>.5&&z>0.0&&z+.20<az)discard;`);};
async function image(src){if(images.has(src))return images.get(src);const im=await new Promise((a,b)=>{const i=new Image();i.onload=()=>a(i);i.onerror=b;i.src=src;});images.set(src,im);if(images.size>80)images.delete(images.keys().next().value);return im;}
async function depth(i){if(depths.has(i))return depths.get(i);const im=await image('/audit/registered-depth/'+String(i).padStart(6,'0')+'.png');dx.clearRect(0,0,320,320);dx.drawImage(im,0,0);const raw=dx.getImageData(0,0,320,320).data;depths.set(i,raw);return raw;}
const ray=new T.Raycaster(),scan=new T.Group();for(const p of room.parts){if(p.label!=='GLOBAL_MESH')continue;const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p.vertices,3));g.setIndex(p.triangles);const m=new T.Mesh(g,new T.MeshBasicMaterial({side:T.DoubleSide}));scan.add(m);}scan.updateMatrixWorld(true);
function pixel(u,v,raw){ray.setFromCamera(new T.Vector2(2*u-1,1-2*v),camera);const z=[];for(let y=-3;y<=3;y++)for(let x=-3;x<=3;x++){const xx=Math.floor(u*320)+x,yy=Math.floor(v*320)+y;if(xx<0||yy<0||xx>=320||yy>=320)continue;const k=(yy*320+xx)*4;if(raw[k+2])z.push((raw[k]*256+raw[k+1])/1000);}z.sort((a,b)=>a-b);if(z.length){const ax=z[Math.floor(z.length*.35)],forward=new T.Vector3(0,0,-1).applyQuaternion(camera.quaternion);return ray.ray.origin.clone().addScaledVector(ray.ray.direction,ax/ray.ray.direction.dot(forward));}const hit=ray.intersectObjects(scan.children)[0];if(hit)return hit.point;throw Error('No measured surface support at '+u+','+v);}
const specs={wall:{t:24,q:[[.45,.12],[.93,.12],[.93,.52],[.45,.52]]},shelf:{t:0,q:[[.50,.326],[.698,.371],[.687,.565],[.494,.638]]},plant:{t:0,q:[[.40,.11],[.81,.14],[.81,.40],[.40,.39]]},fridge:{t:16,q:[[.488,.232],[.727,.233],[.71,.514],[.49,.518]]},table:{t:16,q:[[.10,.582],[.89,.59],[.90,.822],[.018,.811]]},counter:{t:56,q:[[.018,.559],[.514,.62],[.48,.734],[.01,.664]]},cabinet:{t:56,q:[[.08,.711],[.49,.756],[.44,.96],[.014,.847]]},microwave:{t:56,q:[[.049,.231],[.338,.239],[.334,.414],[.057,.398]]},window:{t:56,q:[[.721,.19],[.992,.191],[.99,.823],[.672,.752]]},floor:{t:93,q:[[.43,.61],[.70,.61],[.70,.98],[.25,.98]]}};
for(const [key,a] of Object.entries(specs)){const i=frameAt(session.frames,a.t),raw=await depth(i);setPose(camera,session.frames[i],session.intrinsics);const v=a.q.map(([u,v])=>pixel(u,v,raw)); // Derive a plane from measured points; intersect all authored boundary rays with this fixed world plane.
let normal=new T.Plane().setFromCoplanarPoints(v[0],v[1],v[3]).normal.clone();let centre=v[0].clone();if(['table','counter','floor'].includes(key)){normal.set(0,1,0);const uv={table:[.50,.78],counter:[.30,.64],floor:[.52,.83]}[key];centre=pixel(...uv,raw);}else{normal.y=0;normal.normalize();}if(normal.dot(camera.position.clone().sub(centre))<0)normal.negate();const plane=new T.Plane().setFromNormalAndCoplanarPoint(normal,centre);const vertices=a.q.map(([u,vv],j)=>{ray.setFromCamera(new T.Vector2(2*u-1,1-2*vv),camera);return(ray.ray.intersectPlane(plane,new T.Vector3())||v[j]).addScaledVector(normal,.018);});anchors[key]={referenceFrame:i,referenceTime:session.frames[i].t,pixels:a.q,vertices:vertices.map(v=>v.toArray()),normal:normal.toArray()};}
function makeLayer(target){world.clear();for(const x of solid.children){x.geometry?.dispose();x.material?.dispose();}solid.clear();if(target==='bottle')return;const a=anchors[target],geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(a.vertices.flat(),3));geo.setAttribute('uv',new T.Float32BufferAttribute([0,1,1,1,1,0,0,0],2));geo.setIndex([0,2,1,0,3,2]);layer=new T.Mesh(geo,mat);world.add(layer);}
function pointUV(target,u,v){const a=anchors[target].vertices.map(p=>new T.Vector3().fromArray(p));return a[0].clone().multiplyScalar((1-u)*(1-v)).addScaledVector(a[1],u*(1-v)).addScaledVector(a[2],u*v).addScaledVector(a[3],(1-u)*v);}
function solids(study,t,p){if(study.effect==='coins'){if(!solid.children.length){for(let j=0;j<7;j++){const m=new T.Mesh(new T.CylinderGeometry(.045,.045,.013,32),new T.MeshStandardMaterial({color:0xf9d276,metalness:.55,roughness:.22}));m.material.onBeforeCompile=mat.onBeforeCompile;m.position.copy(pointUV('floor',.4+.10*Math.sin(j*.8),.18+j*.11)).addScaledVector(new T.Vector3().fromArray(anchors.floor.normal),.08);m.userData.id=j;solid.add(m);}}for(const m of solid.children){m.rotation.set(Math.PI/2,0,t*2+m.userData.id*.3);m.visible=camera.position.distanceTo(m.position)>.60;m.scale.setScalar(.9+.1*Math.sin(t*3+m.userData.id));}}
if(study.effect==='fold'){if(!solid.children.length){const m=new T.Mesh(new T.PlaneGeometry(.30,.22),new T.MeshStandardMaterial({color:0xfffbef,roughness:.9,side:T.DoubleSide}));m.geometry.translate(0,.11,0);m.material.onBeforeCompile=mat.onBeforeCompile;solid.add(m);}const m=solid.children[0],a=anchors.table.vertices.map(p=>new T.Vector3().fromArray(p));const x=a[1].clone().sub(a[0]).normalize(),z=new T.Vector3().fromArray(anchors.table.normal),y=z.clone().cross(x).normalize();m.position.copy(pointUV('table',.5,.5)).addScaledVector(z,.025);m.quaternion.setFromRotationMatrix(new T.Matrix4().makeBasis(x,y,z));m.rotateX(-Math.sin(p*Math.PI)*2.4);}}
const overlay=document.createElement('canvas');overlay.width=overlay.height=S;const ox=overlay.getContext('2d');const final=document.createElement('canvas');final.width=final.height=S;const fx=final.getContext('2d');final.id='output';$('#view').append(final);let botanical=null;try{botanical=await image('./assets/inspiration50-botanical.png');}catch{}
const track=new Map(tracks.frames.map(f=>[f.frameIndex,f]));
function handAt(ts){let best=null,dist=Infinity;for(const h of hands){const d=Math.abs(Number(h.unixMs)-ts);if(d<dist){dist=d;best=h;}}const valid=dist<150&&['left','right'].every(k=>best?.[k]?.tracked&&best?.[k]?.valid&&Math.abs(best.ovrSeconds-best[k].sampleTimestamp)<.15);if(!valid)return {valid:false,amount:0.3,separation:null};const a=best.left.rootPosition,b=best.right.rootPosition,separation=Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z);return {valid:true,separation,amount:Math.max(0,Math.min(1,(separation-.24)/.65)),pinch:!!(best.left.pinches||best.right.pinches)};}

async function render(id,sec){const study=catalog.find(s=>s.id===id);if(!study)throw Error('No study');if(current!==id){current=id;makeLayer(study.target);$('#story').textContent=study.story;$('#source').textContent=study.inspiration+' · '+study.input;$('#study').value=id;}
elapsed=Math.max(0,Math.min(sec,study.duration));const time=study.start+elapsed,i=frameAt(session.frames,time),f=session.frames[i];if(last!==i){const im=await image(base+f.image);bg?.dispose();bg=new T.Texture(im);bg.colorSpace=T.SRGBColorSpace;bg.needsUpdate=true;scene.background=bg;const raw=await depth(i);dep?.dispose();dep=new T.DataTexture(new Uint8Array(raw),320,320);dep.flipY=true;dep.needsUpdate=true;dep.minFilter=dep.magFilter=T.NearestFilter;rd.value=dep;last=i;}
setPose(camera,f,session.intrinsics);const hand=handAt(Number(f.timestampUs)/1000);const phase=elapsed/study.duration;ctx.clearRect(0,0,1024,768);paint(ctx,study,{t:phase*8,p:phase,hand,trigger,words,botanical});tex.needsUpdate=true;solids(study,elapsed,phase);renderer.render(scene,camera);
fx.clearRect(0,0,S,S);fx.drawImage(renderer.domElement,0,0);const tr=track.get(i);if(study.target==='bottle'&&tr){await paintBottle(study,tr,i,elapsed);fx.drawImage(overlay,0,0);}
$('#seek').value=phase;$('#clock').textContent=`${study.id}/50 · source ${f.t.toFixed(2)} s · frame ${i+1}/915`;return {capture:session.name,study:study.id,sourceFrame:i,sourceTime:f.t,outputTime:elapsed,hand,bottleTracked:!!tr,target:study.target,anchor:anchors[study.target]||null};}
async function paintBottle(study,tr,i,t){ox.clearRect(0,0,S,S);const u=tr.centroid[0]/1280*S,v=tr.centroid[1]/1280*S,bb=tr.bbox.map(n=>n/1280*S);ox.strokeStyle='#fff';ox.fillStyle='#fff';ox.lineWidth=2;
const mask=await image('/audit/'+tr.mask);const mc=document.createElement('canvas');mc.width=mc.height=S;const mx=mc.getContext('2d',{willReadFrequently:true});mx.drawImage(mask,0,0,S,S);const md=mx.getImageData(0,0,S,S);for(let k=0;k<md.data.length;k+=4){md.data[k+3]=md.data[k];md.data[k]=120;md.data[k+1]=220;md.data[k+2]=210;}mx.putImageData(md,0,0);
if(study.effect==='bottle-color'){ox.globalAlpha=.4+.15*Math.sin(t*3);ox.drawImage(mc,0,0);ox.globalCompositeOperation='source-atop';ox.fillStyle=`hsl(${(t*70+170)%360} 75% 60%)`;ox.fillRect(0,0,S,S);ox.globalCompositeOperation='source-over';ox.globalAlpha=1;}
if(study.effect==='bottle-outline'){ox.shadowColor='#b5ffe5';ox.shadowBlur=12;ox.drawImage(mc,0,0);ox.shadowBlur=0;ox.globalCompositeOperation='destination-out';ox.drawImage(mc,0,0);ox.globalCompositeOperation='source-over';}
const hist=tracks.frames.filter(x=>x.frameIndex<=i&&x.timeSeconds>tr.timeSeconds-1.3);if(['bottle-trace','bottle-spark'].includes(study.effect)){for(let k=1;k<hist.length;k++){ox.globalAlpha=k/hist.length;const a=hist[k-1].centroid,b=hist[k].centroid;ox.beginPath();ox.moveTo(a[0]/1280*S,a[1]/1280*S);ox.lineTo(b[0]/1280*S,b[1]/1280*S);ox.stroke();}ox.globalAlpha=1;}
if(study.effect==='bottle-spark'){for(let j=0;j<35;j++){const a=j*2.4,age=(t*1.5+j*.041)%1,r=age*95;ox.globalAlpha=1-age;ox.fillStyle=j%3?'#fff':'#f7d877';ox.beginPath();ox.arc(u+Math.cos(a)*r,v+Math.sin(a)*r-age*35,1+2*(1-age),0,Math.PI*2);ox.fill();}ox.globalAlpha=1;}
if(study.effect==='bottle-meter'){const movement=hist.length>1?Math.hypot(hist.at(-1).centroid[0]-hist[0].centroid[0],hist.at(-1).centroid[1]-hist[0].centroid[1]):0;ox.beginPath();ox.arc(u,v,bb[2]*.8,-Math.PI/2,-Math.PI/2+Math.min(1,movement/200)*Math.PI*2);ox.stroke();ox.font='20px Arial';ox.fillText('movement',u+bb[2],v-15);ox.font='30px Arial';ox.fillText(Math.round(movement)+' px',u+bb[2],v+20);}
if(study.effect==='bottle-guide'||study.effect==='bottle-outline'){ox.beginPath();ox.moveTo(u+85,v-100);ox.quadraticCurveTo(u+65,v-90,u+20,v-30);ox.lineTo(u+36,v-40);ox.moveTo(u+20,v-30);ox.lineTo(u+20,v-49);ox.stroke();}
}
$('#study').innerHTML=catalog.map(s=>`<option value="${s.id}">${String(s.id).padStart(2,'0')} · ${s.title}</option>`).join('');$('#study').onchange=()=>{playing=false;render(+$('#study').value,0);};$('#seek').oninput=()=>{playing=false;if(!busy){busy=true;render(current,+$('#seek').value*catalog[current-1].duration).finally(()=>busy=false);}};$('#play').onclick=()=>{if(elapsed>=catalog[current-1].duration)elapsed=0;playing=!playing;};$('#trigger').onclick=()=>{trigger++;elapsed=0;playing=true;};$('#apply').onclick=()=>{words=$('#words').value;elapsed=0;playing=true;};let prev=performance.now();async function tick(now){const dt=(now-prev)/1000;prev=now;if(playing&&!busy){busy=true;await render(current,elapsed+dt);busy=false;if(elapsed>=catalog[current-1].duration)playing=false;}requestAnimationFrame(tick);}requestAnimationFrame(tick);
// Video pixels are exported directly, excluding gallery UI. Bottle overlays are combined in a separate final canvas.
window.inspiration50={render,catalog,anchors,session,diagnose:()=>Object.fromEntries(Object.entries(anchors).map(([k,a])=>[k,session.frames.map(f=>{setPose(camera,f,session.intrinsics);const ps=a.vertices.map(v=>new T.Vector3().fromArray(v).project(camera));return {t:f.t,p:ps.map(p=>[p.x,p.y,p.z])};})])),jpeg:()=>final.toDataURL('image/jpeg',.93),png:()=>final.toDataURL('image/png')};await render(1,0);window.inspiration50Ready=true;
