import * as T from 'three';
import {setPose,frameAt} from './math.mjs';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
const base='/sessions/quest-215403/';
const s=await (await fetch(base+'session.json')).json();
const room=await(await fetch(base+'room-geometry.json')).json();
const hands=(await(await fetch(base+'hands.jsonl')).text()).trim().split('\n').map(JSON.parse);
const trackDoc=await(await fetch('/audit/bottle-track.json')).json();const track=new Map(trackDoc.frames.filter(f=>f.timeSeconds>=64&&f.timeSeconds<=68).map(f=>[f.frameIndex,f]));
const c=document.querySelector('#output'),ctx=c.getContext('2d');
const r=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});r.setSize(800,800);r.outputColorSpace=T.SRGBColorSpace;r.toneMapping=T.ACESFilmicToneMapping;
const env=new T.PMREMGenerator(r).fromScene(new RoomEnvironment(),.04).texture;
function scene(){const g=new T.Scene();g.environment=env;g.add(new T.HemisphereLight(0xdceeff,0x304051,2));const l=new T.DirectionalLight(0xffddbb,3);l.position.set(0,4,2);g.add(l);return g;}
const ar=scene(),twin=scene();twin.background=new T.Color('#0c2330');const cam=new T.PerspectiveCamera(),eye=new T.PerspectiveCamera(48,1,.02,60);
const mat=(color)=>new T.MeshStandardMaterial({color,roughness:.26,metalness:.35});const teal=mat('#4be5db'),gold=mat('#ffc363'),white=mat('#e8f3ff'),blue=mat('#658fff'),dark=mat('#163d50');
function mesh(g,geo,m,p=[0,0,0]){const o=new T.Mesh(geo,m);o.position.fromArray(p);g.add(o);return o;}
function line(g,points,color){const o=new T.Line(new T.BufferGeometry().setFromPoints(points.map(p=>new T.Vector3(...p))),new T.LineBasicMaterial({color}));g.add(o);return o;}
const occluders=new T.Group();ar.add(occluders);const scan=new T.Group();twin.add(scan);
for(let i=0;i<34;i++){const p=room.parts[i];if(!p||p.label==='GLOBAL_MESH'||p.label==='CEILING')continue;const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(p.vertices,3));geo.setIndex(p.triangles);geo.computeVertexNormals();const o=mesh(occluders,geo,new T.MeshBasicMaterial({colorWrite:false,side:T.DoubleSide}));o.renderOrder=-1;
const col=p.label==='TABLE'?'#c89042':p.label==='FLOOR'?'#1c4556':'#3a6878';mesh(scan,geo,new T.MeshBasicMaterial({color:col,side:T.DoubleSide,transparent:true,opacity:p.label==='WALL_FACE'?.15:.45}));scan.add(new T.LineSegments(new T.EdgesGeometry(geo),new T.LineBasicMaterial({color:col,transparent:true,opacity:.7})));}
const content=new T.Group();ar.add(content);
const table=room.parts[21];const vv=table.vertices;const top=Math.max(...vv.filter((_,i)=>i%3===1));const lab=new T.Group();content.add(lab);lab.position.set(-.15,top+.007,-.75);
mesh(lab,new T.CylinderGeometry(.24,.25,.025,64),dark,[0,.012,0]);mesh(lab,new T.TorusGeometry(.23,.006,12,72),teal,[0,.032,0]).rotation.x=Math.PI/2;
for(const x of [-.18,.18])mesh(lab,new T.CylinderGeometry(.006,.006,.42,12),gold,[x,.24,0]);mesh(lab,new T.BoxGeometry(.38,.012,.015),gold,[0,.455,0]);const arm=new T.Group();arm.position.y=.445;lab.add(arm);mesh(arm,new T.CylinderGeometry(.003,.003,.3,8),white,[0,-.15,0]);mesh(arm,new T.SphereGeometry(.044,28,20),teal,[0,-.3,0]);
const planets=new T.Group();planets.position.set(.5,.2,0);lab.add(planets);mesh(planets,new T.SphereGeometry(.05,32,24),gold);const orbiters=[];for(let j=0;j<3;j++){const g=new T.Group();planets.add(g);g.rotation.x=.3+j*.3;mesh(g,new T.TorusGeometry(.09+j*.045,.002,8,60),blue).rotation.x=Math.PI/2;const p=mesh(g,new T.SphereGeometry(.012+j*.003,20,12),teal);orbiters.push({p,r:.09+j*.045});}
// Wall-mounted geometry uses the scanned wall plane, not a screen-space sticker.
const wall=room.parts[3];const v=wall.vertices;const wa=new T.Vector3(...v.slice(0,3)),wb=new T.Vector3(...v.slice(3,6)),wc=new T.Vector3(...v.slice(6,9));const normal=wb.clone().sub(wa).cross(wc.clone().sub(wa)).normalize();const wallCenter=new T.Vector3();for(let i=0;i<v.length;i+=3)wallCenter.add(new T.Vector3(...v.slice(i,i+3)));wallCenter.multiplyScalar(3/v.length);if(normal.dot(new T.Vector3(...s.frames[0].position).sub(wallCenter))<0)normal.negate();const wallAid=new T.Group();wallAid.position.copy(wallCenter).addScaledVector(normal,.035);wallAid.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),normal);content.add(wallAid);mesh(wallAid,new T.TorusGeometry(.26,.02,16,80),teal);const wallOrb=mesh(wallAid,new T.IcosahedronGeometry(.12,1),gold);
const sensor=new T.Group();twin.add(sensor);mesh(sensor,new T.BoxGeometry(.12,.07,.06),gold);line(sensor,[[0,0,0],[-.2,-.2,-.4],[.2,-.2,-.4],[0,0,0],[.2,.2,-.4],[-.2,.2,-.4],[0,0,0]],'#4be5db');line(twin,s.frames.map(f=>f.position),'#ffc363');
const secondLab=lab.clone();secondLab.position.set(2.35,-.77,-2.61);secondLab.scale.setScalar(.55);content.add(secondLab);
const depthTarget=mesh(content,new T.TorusKnotGeometry(.12,.027,120,16),blue);depthTarget.visible=false;
const bottleScene=scene();const bottle=new T.Group();bottleScene.add(bottle);mesh(bottle,new T.TorusGeometry(.08,.008,12,80),teal).rotation.x=.9;const bottleMoon=mesh(bottle,new T.IcosahedronGeometry(.023,1),gold,[.08,0,0]);const maskCanvas=document.createElement('canvas');maskCanvas.width=1280;maskCanvas.height=1280;const maskCtx=maskCanvas.getContext('2d');let maskIndex=-1,maskImage;
const cloned=content.clone();twin.add(cloned);
const depthCanvas=document.createElement('canvas');depthCanvas.width=320;depthCanvas.height=320;const depthCtx=depthCanvas.getContext('2d',{willReadFrequently:true});const virtualCanvas=document.createElement('canvas');virtualCanvas.width=800;virtualCanvas.height=800;const virtualCtx=virtualCanvas.getContext('2d',{willReadFrequently:true});const restoreCanvas=document.createElement('canvas');restoreCanvas.width=800;restoreCanvas.height=800;const restoreCtx=restoreCanvas.getContext('2d',{willReadFrequently:true});
const depthMaterial=new T.ShaderMaterial({vertexShader:'varying float axial;void main(){vec4 mv=modelViewMatrix*vec4(position,1.0);axial=-mv.z;gl_Position=projectionMatrix*mv;}',fragmentShader:'varying float axial;void main(){float d=floor(clamp(axial*1000.0,0.0,65535.0));gl_FragColor=vec4(mod(d,256.0)/255.0,floor(d/256.0)/255.0,1.0,1.0);}',side:T.DoubleSide});let depthIndex=-1,depthPixels;window.depthEnabled=true;
async function restoreForeground(i){if(!window.depthEnabled)return 0;if(depthIndex!==i){const img=await new Promise((resolve,reject)=>{const o=new Image();o.onload=()=>resolve(o);o.onerror=reject;o.src='/audit/registered-depth/'+String(i).padStart(6,'0')+'.png';});depthCtx.drawImage(img,0,0);const raw=depthCtx.getImageData(0,0,320,320).data;depthPixels=new Uint8ClampedArray(raw);for(let y=1;y<319;y++)for(let x=1;x<319;x++){let nearest=65536;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const n=((y+dy)*320+x+dx)*4;if(raw[n+2])nearest=Math.min(nearest,raw[n]*256+raw[n+1]);}if(nearest<65536){const n=(y*320+x)*4;depthPixels[n]=nearest>>8;depthPixels[n+1]=nearest&255;depthPixels[n+2]=255;}}depthIndex=i;}
const bg=ar.background;ar.background=null;ar.overrideMaterial=depthMaterial;occluders.visible=false;r.setClearColor(0,0);r.render(ar,cam);virtualCtx.clearRect(0,0,800,800);virtualCtx.drawImage(r.domElement,0,0);const virtual=virtualCtx.getImageData(0,0,800,800).data;ar.background=bg;ar.overrideMaterial=null;occluders.visible=true;restoreCtx.clearRect(0,0,800,800);restoreCtx.drawImage(texture.image,0,0,800,800);const pixels=restoreCtx.getImageData(0,0,800,800);let changed=0;for(let y=0;y<800;y++)for(let x=0;x<800;x++){const p=(y*800+x)*4,d=(Math.floor(y*.4)*320+Math.floor(x*.4))*4;const real=depthPixels[d]*256+depthPixels[d+1],cg=virtual[p]+virtual[p+1]*256;const visible=depthPixels[d+2]&&virtual[p+2]&&real>0&&real+30<cg;pixels.data[p+3]=visible?255:0;if(visible)changed++;}restoreCtx.putImageData(pixels,0,0);ctx.drawImage(restoreCanvas,24,88,784,784);return changed;}
let cached=-1,texture=null;async function frame(i){if(cached===i)return;texture?.dispose();texture=await new T.TextureLoader().loadAsync(base+s.frames[i].image);texture.colorSpace=T.SRGBColorSpace;ar.background=texture;cached=i;}
function sampleAt(ms){let lo=0,hi=hands.length-1;while(lo<hi){const m=Math.ceil((lo+hi)/2);if(hands[m].unixMs<=ms)lo=m;else hi=m-1;}const h=hands[lo];return Math.abs(h.unixMs-ms)<=150?h:null;}
function txt(t,x,y,size=18,col='#d3e4ef',bold=false){ctx.fillStyle=col;ctx.font=`${bold?700:400} ${size}px Arial`;ctx.fillText(t,x,y);}
function copyTransforms(a,b){b.position.copy(a.position);b.quaternion.copy(a.quaternion);b.scale.copy(a.scale);b.visible=a.visible;a.children.forEach((x,i)=>copyTransforms(x,b.children[i]));}
window.renderNewTake=async t=>{const i=frameAt(s.frames,t),f=s.frames[i];await frame(i);setPose(cam,f,s.intrinsics);const h=sampleAt(Number(f.timestampUs)/1000);depthTarget.visible=f.t>=39&&f.t<=50;const depthRay=new T.Vector3(0,-.35,.5).unproject(cam).sub(cam.position).normalize();depthTarget.position.copy(cam.position).addScaledVector(depthRay,.95);depthTarget.rotation.set(f.t*.25,f.t*.35,0);const pinch=!!(h&&['left','right'].some(k=>h[k]?.valid&&h[k]?.tracked&&Math.abs(h.ovrSeconds-h[k].sampleTimestamp)<.15&&h[k]?.pinches));
arm.rotation.z=.6*Math.sin(f.t*3.5);orbiters.forEach(({p,r},j)=>p.position.set(Math.cos(f.t*(.7+j*.35))*r,0,Math.sin(f.t*(.7+j*.35))*r));wallOrb.rotation.set(f.t*.4,f.t*.7,0);wallOrb.scale.setScalar(pinch?1.7:1);teal.emissive.set(pinch?'#176a64':'#000000');
copyTransforms(lab,secondLab);secondLab.position.set(2.35,-.77,-2.61);secondLab.scale.setScalar(.55);copyTransforms(content,cloned);sensor.position.copy(cam.position);sensor.quaternion.copy(cam.quaternion);
ctx.fillStyle='#07121e';ctx.fillRect(0,0,1440,900);txt('SPATIAL SKETCHBOOK',24,29,15,'#68e4d9',true);txt('A room becomes an editable canvas',24,66,32,'#ffffff',true);txt('NEW QUEST TAKE  /  21:54:03',1035,31,16,'#a6bfd0');
r.setClearAlpha(1);r.render(ar,cam);ctx.drawImage(r.domElement,24,88,784,784);const tracked=track.get(i);if(tracked){const [u,v]=tracked.centroid;const ray=new T.Vector3(u/1280*2-1,1-v/1280*2,.5).unproject(cam).sub(cam.position).normalize();bottle.position.copy(cam.position).addScaledVector(ray,.75);bottle.quaternion.copy(cam.quaternion);bottle.scale.setScalar(Math.max(...tracked.bbox.slice(2))*.75/(s.intrinsics.fx*.13));bottleMoon.position.set(Math.cos(f.t*4)*.095,Math.sin(f.t*4)*.095,0);r.setClearAlpha(0);r.render(bottleScene,cam);ctx.drawImage(r.domElement,24,88,784,784);if(maskIndex!==i){maskImage=await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src='/audit/'+tracked.mask;});maskIndex=i;}maskCtx.clearRect(0,0,1280,1280);maskCtx.drawImage(maskImage,0,0);const md=maskCtx.getImageData(0,0,1280,1280);for(let k=0;k<md.data.length;k+=4){md.data[k+3]=md.data[k];}maskCtx.putImageData(md,0,0);maskCtx.globalCompositeOperation='source-in';maskCtx.drawImage(texture.image,0,0);maskCtx.globalCompositeOperation='source-over';ctx.drawImage(maskCanvas,24,88,784,784);txt('2D GREEN-PIXEL TRACK + 3D OVERLAY',44,153,16,'#68ffe5',true);}const depthChanged=await restoreForeground(i);if(depthTarget.visible)txt('AUTHORED DEPTH TARGET / REAL FOREGROUND DEPTH',40,150,14,'#92e8ff',true);txt('REAL CAPTURE + THREE.JS',40,116,15,'#ffffff',true);
eye.position.set(4.7,4.5,5.3);eye.lookAt(1,-.3,-.6);r.render(twin,eye);ctx.drawImage(r.domElement,834,88,580,430);txt('DIGITAL TWIN / CAMERA TRAJECTORY',850,116,15,'#c2fff3',true);
const chapter=t<28?'01 / SURFACE-ANCHORED ANIMATION':t<53?'02 / RECORDED HAND INTERACTION':t<73?'03 / IMAGE-TRACKED AUGMENTATION':'04 / RETURN & INSPECT';
txt(chapter,839,552,18,'#5de0d6',true);txt('Table: miniature pendulum + orbital system',839,586,18);txt('Wall: rotating spatial sculpture',839,615,18);txt('Animation is authored; camera motion is recorded.',839,644,16,'#94b2c6');
txt('CAPTURED HAND SIGNAL',839,693,15,'#5de0d6',true);txt(pinch?'PINCH DETECTED  →  sculpture expands':'Waiting for a valid recorded pinch',839,724,20,pinch?'#ffd17b':'#d3e4ef',true);txt('SDK pinch flags drive color + scale during replay.',839,751,15);txt('Hand/video timing is an estimate, not calibrated.',839,776,15,'#d9b878');
txt('DEPTH / EVIDENCE',839,820,14,'#5de0d6',true);txt('Scan + 5 Hz depth · finite 3×3 point splats',839,844,15);txt('Depth edges unvalidated · A/V offset estimated +188 ms',839,866,15,'#a0b8c9');
ctx.fillStyle='#07121ec9';ctx.fillRect(32,826,762,38);txt(`${f.t.toFixed(2)} s  /  ${s.duration.toFixed(2)} s     •     source frame ${i+1} / ${s.frames.length}`,44,851,16,'#ffffff');ctx.fillStyle='#45dbd0';ctx.fillRect(0,896,1440*t/s.duration,4);
return{sourceFrame:i,sourceTime:f.t,timestampUs:f.timestampUs,pinch,staticOcclusion:true,bottleTrack:!!tracked,depthRestoredPixels:depthChanged};};
window.newTakeSession=s;window.newTakeReady=true;await window.renderNewTake(0);
