import * as T from 'three';
import {setPose,frameAt} from './math.mjs';
const $=s=>document.querySelector(s),base='./sessions/quest-215403/';
const session=await(await fetch(base+'session.json')).json(),room=await(await fetch(base+'room-geometry.json')).json();
if(session.name!=='20261002_215403'||session.synthetic)throw Error('Wrong capture');
const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(1000,1000);renderer.outputColorSpace=T.SRGBColorSpace;$('#view').append(renderer.domElement);renderer.domElement.id='output';
const scene=new T.Scene(),camera=new T.PerspectiveCamera(),scan=new T.Group(),content=new T.Group();scene.add(scan,content);
for(const [index,p] of room.parts.entries()){if(p.label!=='GLOBAL_MESH')continue;const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p.vertices,3));g.setIndex(p.triangles);g.computeVertexNormals();const m=new T.Mesh(g,new T.MeshBasicMaterial({side:T.DoubleSide,colorWrite:false}));m.userData={index,label:p.label};m.renderOrder=-1;scan.add(m);}
scene.updateMatrixWorld(true);
const ray=new T.Raycaster();let anchors=[],selected=0,time=0,playing=false,placing=false,last=-1,busy=false,texture;
const depthSamples=new Map();async function sampleDepth(i){if(depthSamples.has(i))return depthSamples.get(i);const img=await new Promise((ok,no)=>{const im=new Image();im.onload=()=>ok(im);im.onerror=no;im.src='/audit/registered-depth/'+String(i).padStart(6,'0')+'.png';});const c=document.createElement('canvas');c.width=c.height=320;const ctx=c.getContext('2d');ctx.drawImage(img,0,0);const raw=ctx.getImageData(0,0,320,320).data;depthSamples.set(i,raw);return raw;}
for(const t of [0,16,48,56])await sampleDepth(frameAt(session.frames,t));
function surface(t,u,v,normalOverride){const f=session.frames[frameAt(session.frames,t)];setPose(camera,f,session.intrinsics);ray.setFromCamera(new T.Vector2(2*u-1,1-2*v),camera);const hit=ray.intersectObjects(scan.children)[0];if(!hit)throw Error('No captured surface at this pixel');const raw=depthSamples.get(frameAt(session.frames,t));let axial=0;if(raw){const ds=[];for(let dy=-5;dy<=5;dy++)for(let dx=-5;dx<=5;dx++){const x=Math.floor(u*320)+dx,y=Math.floor(v*320)+dy;if(x<0||y<0||x>=320||y>=320)continue;const k=(y*320+x)*4;if(raw[k+2])ds.push(raw[k]*256+raw[k+1]);}ds.sort((a,b)=>a-b);if(ds.length)axial=ds[Math.floor(ds.length*.2)]/1000;}if(axial){const forward=new T.Vector3(0,0,-1).applyQuaternion(camera.quaternion);hit.point.copy(ray.ray.origin).addScaledVector(ray.ray.direction,axial/ray.ray.direction.dot(forward));}const n=hit.face.normal.clone().transformDirection(hit.object.matrixWorld);if(n.dot(camera.position.clone().sub(hit.point))<0)n.negate();if(Math.abs(n.y)<.6){n.y=0;n.normalize();}else if(Math.abs(n.y)>.85){n.set(0,Math.sign(n.y),0);}if(normalOverride)n.fromArray(normalOverride).normalize();let up=new T.Vector3(0,1,0);if(Math.abs(n.y)>.75){up=camera.position.clone().sub(hit.point).negate();up.y=0;up.normalize();}up.addScaledVector(n,-up.dot(n)).normalize();const right=up.clone().cross(n).normalize();up=n.clone().cross(right).normalize();return {position:hit.point.clone().addScaledVector(n,.025).toArray(),quaternion:new T.Quaternion().setFromRotationMatrix(new T.Matrix4().makeBasis(right,up,n)).toArray(),surfaceNormal:n.toArray(),placementDepth:axial||null,sourceFrame:frameAt(session.frames,t),sourcePixel:[u,v],meshPart:hit.object.userData.index};}
const presets=[
 {name:'Wall / quiet agent',t:0,u:.18,v:.35,width:.85,text:'All caught up.\nYour evening is clear.'},
 {name:'Shelf / finding',t:0,u:.485,v:.51,width:.22,normalOverride:[.8473,0,.5311],text:'Books'},
 {name:'Fridge / reminder',t:16,u:.69,v:.38,width:.38,text:'Use today\nVegetables · leftovers'},
 {name:'Table / next step',t:16,u:.62,v:.77,width:.42,text:'Dinner for two\nSet out two plates.'},
 {name:'Wall / return',t:48,u:.72,v:.63,width:.55,text:'One thing for tomorrow\nBring your notebook.'},
 {name:'Drawer / contents',t:56,u:.34,v:.85,width:.32,text:'Utensils\nEverything in reach.'}
];
function defaults(){return presets.map(p=>({...p,...surface(p.t,p.u,p.v,p.normalOverride)}));}
const depthUniform={value:null};let depthTexture;function depthAware(material){material.onBeforeCompile=shader=>{shader.uniforms.realDepth=depthUniform;shader.vertexShader='varying float surfaceDepth;\n'+shader.vertexShader.replace('#include <project_vertex>','#include <project_vertex>\nsurfaceDepth=-mvPosition.z;');shader.fragmentShader='uniform sampler2D realDepth; varying float surfaceDepth;\n'+shader.fragmentShader.replace('#include <clipping_planes_fragment>','#include <clipping_planes_fragment>\nvec4 rd=texture2D(realDepth,gl_FragCoord.xy/1000.0);float meters=(rd.r*65280.0+rd.g*255.0)/1000.0;if(rd.b>.5 && meters>.0 && meters+.16<surfaceDepth)discard;');};return material;}
function rebuild(){for(const x of [...content.children]){x.geometry.dispose();x.material.map.dispose();x.material.dispose();content.remove(x);}for(const [i,a] of anchors.entries()){const c=document.createElement('canvas');c.width=1536;c.height=280;const x=c.getContext('2d');x.font='500 78px Arial';c.width=Math.ceil(Math.max(...a.text.split('\n').map(line=>x.measureText(line).width))+100);x.clearRect(0,0,c.width,c.height);x.fillStyle='white';x.textAlign='center';x.textBaseline='middle';a.text.split('\n').slice(0,3).forEach((line,j)=>{x.font=`${j===0?'500':'400'} ${j===0?78:55}px Arial`;x.fillText(line,c.width/2,85+j*100,c.width-40);});const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;const m=new T.Mesh(new T.PlaneGeometry(a.width,a.width*c.height/c.width),depthAware(new T.MeshBasicMaterial({map:tex,transparent:true,depthTest:false,depthWrite:false,side:T.FrontSide,polygonOffset:true,polygonOffsetFactor:-2})));m.position.fromArray(a.position);m.quaternion.fromArray(a.quaternion);m.userData.anchor=i;content.add(m);}$('#anchors').innerHTML=anchors.map((a,i)=>`<option value="${i}">${a.name.replace(/[<>]/g,'')}</option>`).join('');$('#anchors').value=selected;sync();}
function sync(){const a=anchors[selected];$('#text').value=a.text;$('#width').value=a.width;}
const key='quest-215403-surface-text-v1';try{const saved=JSON.parse(localStorage.getItem(key));anchors=saved?.capture===session.name?saved.anchors:defaults();}catch{anchors=defaults();}rebuild();
async function render(t){time=Math.max(0,Math.min(session.duration,t));const i=frameAt(session.frames,time),f=session.frames[i];if(i!==last){const next=await new T.TextureLoader().loadAsync(base+f.image);next.colorSpace=T.SRGBColorSpace;texture?.dispose();texture=next;scene.background=texture;const raw=await sampleDepth(i),filled=new Uint8Array(raw);for(let y=0;y<320;y++)for(let x=0;x<320;x++){let closest=65536;for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++){const xx=x+dx,yy=y+dy;if(xx<0||yy<0||xx>=320||yy>=320)continue;const k=(yy*320+xx)*4;if(raw[k+2])closest=Math.min(closest,raw[k]*256+raw[k+1]);}const k=(y*320+x)*4;if(closest<65536){filled[k]=closest>>8;filled[k+1]=closest&255;filled[k+2]=255;filled[k+3]=255;}}const dep=new T.DataTexture(filled,320,320);dep.flipY=true;dep.needsUpdate=true;dep.minFilter=T.NearestFilter;dep.magFilter=T.NearestFilter;depthTexture?.dispose();depthTexture=dep;depthUniform.value=dep;last=i;}setPose(camera,f,session.intrinsics);renderer.render(scene,camera);$('#time').value=time;$('#clock').textContent=`${f.t.toFixed(2)} s · frame ${i+1}/915`;return{capture:session.name,frame:i,time:f.t,anchors:anchors.map(a=>({position:a.position,quaternion:a.quaternion})),camera:f.position};}
$('#anchors').onchange=async e=>{selected=+e.target.value;sync();await render(anchors[selected].t);};$('#apply').onclick=()=>{anchors[selected].text=$('#text').value;anchors[selected].width=+$('#width').value;rebuild();render(time);};$('#save').onclick=()=>{localStorage.setItem(key,JSON.stringify({capture:session.name,anchors}));$('#status').textContent='Saved for this capture.';};$('#reset').onclick=()=>{anchors=defaults();selected=0;rebuild();render(time);};$('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({capture:session.name,coordinateSystem:session.coordinateSystem,anchors},null,2)],{type:'application/json'}));a.download='quest-215403-surface-anchors.json';a.click();URL.revokeObjectURL(a.href);};
$('#place').onclick=()=>{playing=false;placing=true;$('#status').textContent='Click the physical surface for this text.';};renderer.domElement.onclick=e=>{if(!placing)return;const b=renderer.domElement.getBoundingClientRect();try{Object.assign(anchors[selected],surface(time,(e.clientX-b.left)/b.width,(e.clientY-b.top)/b.height),{t:time});placing=false;rebuild();render(time);$('#status').textContent='Anchored to recorded room geometry.';}catch(e){$('#status').textContent=e.message;}};
$('#time').oninput=e=>{playing=false;if(!busy){busy=true;render(+e.target.value).finally(()=>busy=false);}};$('#play').onclick=()=>{playing=!playing;$('#play').textContent=playing?'Pause':'Play';};let stamp=performance.now();async function tick(now){const dt=(now-stamp)/1000;stamp=now;if(playing&&!busy){busy=true;await render(time+dt);busy=false;if(time>=session.duration)playing=false;}requestAnimationFrame(tick);}requestAnimationFrame(tick);
window.surfaceText={render,get anchors(){return anchors;},session,surface};await render(0);window.surfaceTextReady=true;
